### PR TITLE
Prevent tsc from narrowing nested switch statements v2

### LINKED ISSUE #111: Compiling flattened JSON results in type error
Given this JSON:

`app/routes/Users/components/UserStatsSubRoute/components/StatsGraph/lang/en-US.translations.json`:
```json
{
  "infoIconTooltip": {
    "message": "Part of your {title, select, Views {views} Downloads {downloads}} come from being {title, select, Views {viewed in} Downloads {downloaded from}} the following applications."
  }
}

```

If we compile, it generates valid TS:

```sh-session
$ intlc compile --locale en-US app/routes/Users/components/UserStatsSubRoute/components/StatsGraph/lang/en-US.translations.json | prettier --parser=babel
export const infoIconTooltip: (x: { title: 'Views' | 'Downloads' }) => string = (x) =>
  `Part of your ${(() => {
    switch (x.title) {
      case 'Views':
        return `views`;
      case 'Downloads':
        return `downloads`;
    }
  })()} come from being ${(() => {
    switch (x.title) {
      case 'Views':
        return `viewed in`;
      case 'Downloads':
        return `downloaded from`;
    }
  })()} the following applications.`;
```

However, if we flatten and then compile, the generated TS has a type error:

```sh-session
$ intlc flatten app/routes/Users/components/UserStatsSubRoute/components/StatsGraph/lang/en-US.translations.json > flattened.json

$ intlc compile --locale en-US flattened.json | prettier --parser=babel
export const infoIconTooltip: (x: { title: 'Views' | 'Downloads' }) => string = (x) =>
  `${(() => {
    switch (x.title) {
      case 'Views':
        return `${(() => {
          switch (x.title) {
            case 'Views':
              return `Part of your views come from being viewed in the following applications.`;
            case 'Downloads':
              return `Part of your views come from being downloaded from the following applications.`;
          }
        })()}`;
      case 'Downloads':
        return `${(() => {
          switch (x.title) {
            case 'Views':
              return `Part of your downloads come from being viewed in the following applications.`;
            case 'Downloads':
              return `Part of your downloads come from being downloaded from the following applications.`;
          }
        })()}`;
    }
  })()}`;
```

image

### PR DESCRIPTION
**Pull request by samhh**
Fixes #111 by annotating plain switch conditions with `as typeof`. Supercedes #133 which solved the same problem with IIFEs. A test which is fixed by the final commit is included as suggested.

Includes some refactoring to try and make the JS compiler a bit more extensible. Not entirely sold on this approach but it works without sacrificing the JS compiler's independence.

### CODE REVIEW

File: lib/Intlc/Backend/TypeScript/Compiler.hs [hunk 1]
```diff
@@ -15,9 +15,12 @@ import           Prelude                           hiding (Type)
...
 
 compileNamedExport :: InterpStrat -> Locale -> Text -> ICU.Message -> Text
-compileNamedExport x l k v =
-  "export const " <> n <> ": " <> compileTypeof x v <> " = " <> arg <> " => " <> r
-  where (n, r) = JS.compileStmtPieces x l k v
+compileNamedExport s l k v = JS.compileStmt o s l k v
+  where o = JS.emptyOverrides { JS.stmtOverride = Just stmt, JS.matchLitCondOverride = Just matchLitCond }
+        stmt n r = "export const " <> n <> ": " <> compileTypeof s v <> " = " <> arg <> " => " <> r
+        -- Prevents TypeScript from narrowing, which absent this causes some
+        -- nested switch output to fail typechecking.
```
Comment (Magellol) [inline lib/Intlc/Backend/TypeScript/Compiler.hs:22]: As far as I understand TS is doing the right thing in normal circumstances (e.g application code) but here since we duplicate code on purpose, it doesn't suit us right?

**Review by Magellol — APPROVED** [review]

File: lib/Intlc/Backend/TypeScript/Compiler.hs (hunk 1 above)
Comment (samhh) [reply lib/Intlc/Backend/TypeScript/Compiler.hs:22]: Correct. We could complicate the compiler to remove unneeded nested cases, but the current compiler implementation tries to be as simple as possible.

**Comment by OliverJAsh** [comment]
In the future we might be able to use `satisfies` operator instead of a type assertion: https://github.com/microsoft/TypeScript/issues/47920#:~:text=hopefully%20become%20obvious.-,Safe%20Upcast,-Frequently%20in%20places
