### PR TITLE
Report all dataset parse failures

### LINKED ISSUE #113: Multiple error reporting
Given:

```json
{
  "f": {
    "message": "{x, bad1}"
  },
  "g": {
    "message": "{y, bad2}"
  }
}
```

We currently fail at the first sign of trouble:

```console
$ intlc compile <file> -l <locale>
f:1:5:
  |
1 | {x, bad1}
  |     ^^^^^
unexpected "bad1}"
expecting "boolean", "date", "number", "plural", "select", "selectordinal", "time", or white space
```

Ideally we'd be able to continue trying to parse messages, collating all failures and reporting them together at the end:

```console
$ intlc compile <file> -l <locale>
2 messages failed to compile:

f:1:5:
  |
1 | {x, bad1}
  |     ^^^^^
unexpected "bad1}"
expecting "boolean", "date", "number", "plural", "select", "selectordinal", "time", or white space

g:1:5:
  |
1 | {y, bad2}
  |     ^^^^^
unexpected "bad2}"
expecting "boolean", "date", "number", "plural", "select", "selectordinal", "time", or white space
```

Better yet the line numbers/etc could correlate to the JSON input:

```console
$ intlc compile <file> -l <locale>
2 messages failed to compile:

<file>:3:5:
  |
3 |     "message": {x, bad1}
  |                    ^^^^^
unexpected "bad1}"
expecting "boolean", "date", "number", "plural", "select", "selectordinal", "time", or white space

<file>:6:5:
  |
6 |     "message": {y, bad2}
  |                    ^^^^^
unexpected "bad2}"
expecting "boolean", "date", "number", "plural", "select", "selectordinal", "time", or white space
```

### PR DESCRIPTION
**Pull request by samhh**
Closes #113, though I'd still like to improve the story around line numbers and such.

Given:

```json
{
  "f": {
    "message": "{x, bad1}"
  },
  "g": {
    "message": "{y, bad2}"
  }
}
```

Before:

```console
$ intlc compile <file> -l <locale>
f:1:5:
  |
1 | {x, bad1}
  |     ^^^^^
unexpected "bad1}"
expecting "boolean", "date", "number", "plural", "select", "selectordinal", "time", or white space
```

After:

```console
$ intlc compile <file> -l <locale>
f:1:5:
  |
1 | {x, bad1}
  |     ^^^^^
unexpected "bad1}"
expecting "boolean", "date", "number", "plural", "select", "selectordinal", "time", or white space

g:1:5:
  |
1 | {y, bad2}
  |     ^^^^^
unexpected "bad2}"
expecting "boolean", "date", "number", "plural", "select", "selectordinal", "time", or white space
```

### CODE REVIEW

File: lib/Intlc/Parser.hs [hunk 1]
```diff
@@ -41,21 +45,19 @@ failingWith :: MonadParsec e s m => Int -> e -> m a
...
-printErr FailedJsonParse        = "Failed to parse JSON"
-printErr (FailedMessageParse e) = errorBundlePretty e
+printErr FailedJsonParse         = "Failed to parse JSON"
+printErr (FailedDatasetParse es) = intercalate "\n" . toList . fmap errorBundlePretty $ es
 
 parseDataset :: ByteString -> Either ParseFailure (Dataset Translation)
 parseDataset = parse' <=< decode'
   where decode' = maybeToRight FailedJsonParse . decode
-        parse' = M.traverseWithKey ((first FailedMessageParse .) . parseTranslationFor)
+        parse' = toEither . first FailedDatasetParse . M.traverseWithKey ((validationNel .) . parseTranslationFor)
```
Comment (OliverJAsh) [inline lib/Intlc/Parser.hs:54]: Is it worth having tests for this behaviour?

**Review by OliverJAsh — APPROVED** [review]
